### ISSUE TITLE
Is there any way to get validation as bool?

### ISSUE THREAD

**Issue by 2shrestha22** [TheMisir/form-validator#18]
Is it possible to get bool also from validation result? I need to validate form in logic also not only in UI so if there is something like `ValidationBuilder().email().isValid('my@email.com')` is will be nice. Can this be achieved using extension?

**Comment by themisir** [comment]
Yes of course.

```dart
ValidationBuilde()
  .email()
  .test('my@email.com')
```

**Comment by 2shrestha22** [comment]
I think it returns `String`, isn't it?

**Comment by themisir** [comment]
> I think it returns `String`, isn't it?

If the validation passed it will return null otherwise the error message will be returned. So you can check if value equals to null or not like that:

```dart
if (ValidationBuilde().email().test('my@email.com') == null) {
  // validation passed
}
```

Or:

```dart
final result = ValidationBuilde().email().test('my@email.com');

if (result == null) {
  // Validation passed
} else {
  print('Validation error: $result');
}
```

**Comment by 2shrestha22** [comment]
Okay, thank you for the solution. Btw it will be a nice feature to add.
