### ISSUE TITLE
Add a method to add locale to the supported list (instead of using the globalLocale

### ISSUE THREAD

**Issue by dreemz-dev** [TheMisir/form-validator#38]
**Is your feature request related to a problem? Please describe.**
If I want to add a custom locale and switch to another local on runtime,
When the user change locale, for custom local I need to use the globalLocale, while for supported locale I need to use setLoacel() 

**Describe the solution you'd like**
I want a method like:
ValidationBuilder.addLocale(FormValidatorLocale customLocale);

**Comment by themisir** [comment]
ValidationBuilder already supports using "local" locales by providing them as constructor parameter:

```dart
ValidationBuilder(locale: customLocale)
```

If you need more "flexibility" you can write some helper function like this and use on your app:

```dart
const customLocales = {
  'x': MyLocale(),
};

ValidationBuilder validator(BuildContext context) {
  final currentLocale = Locale.of(context);

  if (customLocales.containsKey(currentLocale.languageCode)) {
    return ValidationBuilder(locale: customLocales[currentLocale.languageCode]);
  }

  return ValidationBuilder(localeName: currentLocale.languageCode);
}
```
