### ISSUE TITLE
Adding more language translations

### ISSUE THREAD

**Issue by themisir** [TheMisir/form-validator#4]
I need help to add new languages to this library. You can simply duplicate any file in [`/lib/src/i18n`](https://github.com/TheMisir/form-validator/tree/master/lib/src/i18n) (for example [`en.dart`](https://github.com/TheMisir/form-validator/blob/master/lib/src/i18n/en.dart)) and translate messages. Then please create pull request.

Thanks.

**Comment by masseelch** [comment]
Added for german.
