### ISSUE TITLE
How to add a prefix?

### ISSUE THREAD

**Issue by ariefsn** [TheMisir/form-validator#51]
**Is your feature request related to a problem? Please describe.**
How to add a prefix to the message? eg. Field-A is required, Field-B is required, etc.

**Describe the solution you'd like**
Perhaps, all of the rule can have field as first parameter. So that field can be add to the message.

```dart
  ValidationBuilder required() => add((String? field, value) {
        return (value ?? "").isEmpty ? '${(field ?? "Field")} is required' : null;
      });

   ValidationBuilder(prefix: "Field-A").required()
   ValidationBuilder(prefix: "Field-B").required()
```

**Comment by themisir** [comment]
Hey @ariefsn, the feature you've asking for is not supported or is not planned to be supported anytime soon. I am sorry for that but at this point I can't change the core design of the system.

**Comment by ariefsn** [comment]
oh ok.
no probs, thanks for the answer @themisir
we can close this.
thanks for the package 👍🏻

**Comment by themisir** [comment]
Appreciate it 😇 To put more context the reason why it's not possible at the moment is, the package now supports multiple language translations in which adding a new feature would mean having to support it in all of them is not feasible - the translations have been provided by various contributors.
